// Data courses untuk Landing Page
import CourseImg1 from "../assets/images/course_english_running.png"
import CourseImg2 from "../assets/images/course_japanese_yoga.png"
import CourseImg3 from "../assets/images/course_korean_basketball.png"
import CourseImg4 from "../assets/images/course_german_nature.png"

export const landingCourses = [
    {
        id: 1,
        image: CourseImg1,
        category: "sports",
        title: "Panduan Lari Marathon untuk Pemula: Dari 0 ke 42K dalam 12 Minggu",
        instructor: "Budi Santoso",
        date: "2 bulan lalu",
        rating: 4.8,
        ratingCount: "9.5k rating",
        materialsCount: "20 materi+",
        duration: "10 jam",
        level: "Semua kalangan",
        price: "Rp. 99.000"
    },
    {
        id: 2,
        image: CourseImg2,
        category: "kebugaran",
        title: "Teknik Dasar Yoga untuk Fleksibilitas dan Ketenangan Mental",
        instructor: "Sari Devi",
        date: "2 bulan lalu",
        rating: 4.8,
        ratingCount: "9.5k rating",
        materialsCount: "20 materi+",
        duration: "10 jam",
        level: "Semua kalangan",
        price: "Rp. 59.000"
    },
    {
        id: 3,
        image: CourseImg3,
        category: "kebugaran",
        title: "Latihan Intensif HIIT: Bakar Kalori Maksimal dalam 30 Menit",
        instructor: "Rian Wijaya",
        date: "2 bulan lalu",
        rating: 4.8,
        ratingCount: "9.5k rating",
        materialsCount: "20 materi+",
        duration: "10 jam",
        level: "Semua kalangan",
        price: "Rp. 79.000"
    },
    {
        id: 4,
        image: CourseImg4,
        category: "nutrisi",
        title: "Nutrisi Olahraga: Atur Pola Makan untuk Performa Atletis",
        instructor: "Dr. Andi Pratama",
        date: "2 bulan lalu",
        rating: 4.8,
        ratingCount: "9.5k rating",
        materialsCount: "20 materi+",
        duration: "10 jam",
        level: "Semua kalangan",
        price: "Rp. 50.000"
    },
    {
        id: 5,
        image: CourseImg1,
        category: "sports",
        title: "Lari Jarak Jauh: Teknik dan Strategi untuk Atlet Menengah",
        instructor: "Budi Santoso",
        date: "1 bulan lalu",
        rating: 4.9,
        ratingCount: "1.2k rating",
        materialsCount: "15 materi+",
        duration: "8 jam",
        level: "Menengah",
        price: "Rp. 129.000"
    },
    {
        id: 6,
        image: CourseImg2,
        category: "mental",
        title: "Mindfulness Berbasis Olahraga: Kelola Stress dengan Aktivitas Fisik",
        instructor: "Sari Devi",
        date: "3 minggu lalu",
        rating: 4.7,
        ratingCount: "800 rating",
        materialsCount: "12 materi+",
        duration: "5 jam",
        level: "Semua kalangan",
        price: "Rp. 49.000"
    },
    {
        id: 7,
        image: CourseImg3,
        category: "kebugaran",
        title: "Calisthenics Fundamental: Kuasai Tubuhmu Tanpa Beban Luar",
        instructor: "Rian Wijaya",
        date: "1 bulan lalu",
        rating: 4.8,
        ratingCount: "2.1k rating",
        materialsCount: "25 materi+",
        duration: "12 jam",
        level: "Semua kalangan",
        price: "Rp. 89.000"
    },
    {
        id: 8,
        image: CourseImg4,
        category: "nutrisi",
        title: "Meal Prep Sehat: Hemat Waktu dan Uang untuk Hidup Lebih Baik",
        instructor: "Dr. Andi Pratama",
        date: "2 minggu lalu",
        rating: 4.9,
        ratingCount: "3.5k rating",
        materialsCount: "18 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 75.000"
    },
    {
        id: 9,
        image: CourseImg1,
        category: "sports",
        title: "Teknik Dasar Sepak Bola: Dari Dribbling hingga Shooting",
        instructor: "Ahmad Fauzi",
        date: "1 bulan lalu",
        rating: 4.7,
        ratingCount: "1.8k rating",
        materialsCount: "22 materi+",
        duration: "9 jam",
        level: "Pemula",
        price: "Rp. 85.000"
    },
    {
        id: 10,
        image: CourseImg2,
        category: "kebugaran",
        title: "Pilates untuk Postur Tubuh yang Lebih Baik",
        instructor: "Linda Wijaya",
        date: "3 minggu lalu",
        rating: 4.8,
        ratingCount: "1.5k rating",
        materialsCount: "18 materi+",
        duration: "7 jam",
        level: "Semua kalangan",
        price: "Rp. 69.000"
    },
    {
        id: 11,
        image: CourseImg3,
        category: "sports",
        title: "Basket untuk Pemula: Fundamental dan Teknik Dasar",
        instructor: "Doni Prasetyo",
        date: "2 minggu lalu",
        rating: 4.6,
        ratingCount: "950 rating",
        materialsCount: "16 materi+",
        duration: "8 jam",
        level: "Pemula",
        price: "Rp. 79.000"
    },
    {
        id: 12,
        image: CourseImg4,
        category: "nutrisi",
        title: "Diet Seimbang: Panduan Lengkap Nutrisi Harian",
        instructor: "Dr. Sarah Amelia",
        date: "1 bulan lalu",
        rating: 4.9,
        ratingCount: "2.8k rating",
        materialsCount: "24 materi+",
        duration: "10 jam",
        level: "Semua kalangan",
        price: "Rp. 95.000"
    },
    {
        id: 13,
        image: CourseImg1,
        category: "mental",
        title: "Meditasi untuk Atlet: Tingkatkan Fokus dan Performa",
        instructor: "Yoga Pratama",
        date: "2 minggu lalu",
        rating: 4.8,
        ratingCount: "1.3k rating",
        materialsCount: "14 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 55.000"
    },
    {
        id: 14,
        image: CourseImg2,
        category: "kebugaran",
        title: "Zumba Dance Fitness: Bakar Kalori dengan Cara Menyenangkan",
        instructor: "Maria Santos",
        date: "3 minggu lalu",
        rating: 4.7,
        ratingCount: "2.2k rating",
        materialsCount: "20 materi+",
        duration: "8 jam",
        level: "Semua kalangan",
        price: "Rp. 65.000"
    },
    {
        id: 15,
        image: CourseImg3,
        category: "sports",
        title: "Renang untuk Pemula: Teknik Gaya Bebas dan Dada",
        instructor: "Eko Saputra",
        date: "1 bulan lalu",
        rating: 4.8,
        ratingCount: "1.7k rating",
        materialsCount: "19 materi+",
        duration: "9 jam",
        level: "Pemula",
        price: "Rp. 89.000"
    },
    {
        id: 16,
        image: CourseImg4,
        category: "nutrisi",
        title: "Suplemen Olahraga: Panduan Memilih yang Tepat",
        instructor: "Dr. Andi Pratama",
        date: "2 minggu lalu",
        rating: 4.6,
        ratingCount: "1.1k rating",
        materialsCount: "15 materi+",
        duration: "5 jam",
        level: "Menengah",
        price: "Rp. 70.000"
    },
    {
        id: 17,
        image: CourseImg1,
        category: "mental",
        title: "Manajemen Stress untuk Kehidupan Sehat",
        instructor: "Psikolog Dewi",
        date: "3 minggu lalu",
        rating: 4.9,
        ratingCount: "2.5k rating",
        materialsCount: "17 materi+",
        duration: "7 jam",
        level: "Semua kalangan",
        price: "Rp. 60.000"
    },
    {
        id: 18,
        image: CourseImg2,
        category: "kebugaran",
        title: "Stretching dan Flexibility: Cegah Cedera Olahraga",
        instructor: "Fitri Handayani",
        date: "1 bulan lalu",
        rating: 4.7,
        ratingCount: "1.4k rating",
        materialsCount: "16 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 45.000"
    },
    {
        id: 19,
        image: CourseImg3,
        category: "sports",
        title: "Bulu Tangkis: Teknik Smash dan Strategi Permainan",
        instructor: "Taufik Hidayat",
        date: "2 minggu lalu",
        rating: 4.9,
        ratingCount: "3.2k rating",
        materialsCount: "21 materi+",
        duration: "10 jam",
        level: "Menengah",
        price: "Rp. 99.000"
    },
    {
        id: 20,
        image: CourseImg4,
        category: "nutrisi",
        title: "Hidrasi Optimal: Pentingnya Air untuk Performa",
        instructor: "Dr. Sarah Amelia",
        date: "3 minggu lalu",
        rating: 4.6,
        ratingCount: "890 rating",
        materialsCount: "12 materi+",
        duration: "4 jam",
        level: "Semua kalangan",
        price: "Rp. 40.000"
    },
    {
        id: 21,
        image: CourseImg1,
        category: "mental",
        title: "Tidur Berkualitas untuk Recovery Optimal",
        instructor: "Dr. Bambang",
        date: "1 bulan lalu",
        rating: 4.8,
        ratingCount: "1.9k rating",
        materialsCount: "15 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 55.000"
    },
    {
        id: 22,
        image: CourseImg2,
        category: "kebugaran",
        title: "Bodyweight Training: Latihan Tanpa Alat di Rumah",
        instructor: "Rian Wijaya",
        date: "2 minggu lalu",
        rating: 4.8,
        ratingCount: "2.3k rating",
        materialsCount: "23 materi+",
        duration: "11 jam",
        level: "Semua kalangan",
        price: "Rp. 75.000"
    },
    {
        id: 23,
        image: CourseImg3,
        category: "sports",
        title: "Voli: Teknik Passing, Smash, dan Blocking",
        instructor: "Rivan Nurmulki",
        date: "3 minggu lalu",
        rating: 4.7,
        ratingCount: "1.6k rating",
        materialsCount: "18 materi+",
        duration: "8 jam",
        level: "Pemula",
        price: "Rp. 80.000"
    },
    {
        id: 24,
        image: CourseImg4,
        category: "nutrisi",
        title: "Protein untuk Pembentukan Otot: Panduan Lengkap",
        instructor: "Dr. Andi Pratama",
        date: "1 minggu lalu",
        rating: 4.9,
        ratingCount: "2.7k rating",
        materialsCount: "19 materi+",
        duration: "7 jam",
        level: "Menengah",
        price: "Rp. 85.000"
    },
    {
        id: 25,
        image: CourseImg1,
        category: "mental",
        title: "Motivasi Diri: Tetap Konsisten dalam Olahraga",
        instructor: "Coach Hendra",
        date: "2 minggu lalu",
        rating: 4.8,
        ratingCount: "2.1k rating",
        materialsCount: "16 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 50.000"
    },
    {
        id: 26,
        image: CourseImg2,
        category: "kebugaran",
        title: "Core Strength: Latihan Perut dan Punggung yang Efektif",
        instructor: "Fitri Handayani",
        date: "1 bulan lalu",
        rating: 4.7,
        ratingCount: "1.8k rating",
        materialsCount: "17 materi+",
        duration: "7 jam",
        level: "Semua kalangan",
        price: "Rp. 65.000"
    },
    {
        id: 27,
        image: CourseImg3,
        category: "sports",
        title: "Tenis Meja: Teknik Forehand dan Backhand",
        instructor: "Sutrisno",
        date: "3 minggu lalu",
        rating: 4.6,
        ratingCount: "1.2k rating",
        materialsCount: "14 materi+",
        duration: "6 jam",
        level: "Pemula",
        price: "Rp. 60.000"
    },
    {
        id: 28,
        image: CourseImg4,
        category: "nutrisi",
        title: "Karbohidrat Sehat: Energi untuk Aktivitas Harian",
        instructor: "Dr. Sarah Amelia",
        date: "2 minggu lalu",
        rating: 4.8,
        ratingCount: "1.5k rating",
        materialsCount: "16 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 55.000"
    },
    {
        id: 29,
        image: CourseImg1,
        category: "mental",
        title: "Visualisasi untuk Mencapai Target Fitness",
        instructor: "Yoga Pratama",
        date: "1 minggu lalu",
        rating: 4.9,
        ratingCount: "1.7k rating",
        materialsCount: "13 materi+",
        duration: "5 jam",
        level: "Semua kalangan",
        price: "Rp. 45.000"
    },
    {
        id: 30,
        image: CourseImg2,
        category: "mental",
        title: "Breathing Techniques: Teknik Pernapasan untuk Relaksasi",
        instructor: "Sari Devi",
        date: "2 minggu lalu",
        rating: 4.8,
        ratingCount: "1.4k rating",
        materialsCount: "14 materi+",
        duration: "5 jam",
        level: "Semua kalangan",
        price: "Rp. 48.000"
    },
    {
        id: 31,
        image: CourseImg3,
        category: "mental",
        title: "Positive Mindset: Bangun Mental Juara",
        instructor: "Coach Hendra",
        date: "3 minggu lalu",
        rating: 4.7,
        ratingCount: "1.6k rating",
        materialsCount: "15 materi+",
        duration: "6 jam",
        level: "Semua kalangan",
        price: "Rp. 52.000"
    },
    {
        id: 32,
        image: CourseImg4,
        category: "mental",
        title: "Overcoming Anxiety: Atasi Kecemasan dengan Olahraga",
        instructor: "Psikolog Dewi",
        date: "1 bulan lalu",
        rating: 4.9,
        ratingCount: "2.3k rating",
        materialsCount: "18 materi+",
        duration: "7 jam",
        level: "Semua kalangan",
        price: "Rp. 65.000"
    }
]
